---
- name: Deploy Calculator container locally
  hosts: local
  tasks:
    - name: Ensure Docker Python SDK is installed
      pip:
        name: docker
        executable: pip3

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: chandrimanandi/calculator
        tag: latest
        source: pull

    - name: Stop and remove existing container
      docker_container:
        name: calculator
        state: absent

    - name: Run the Calculator container
      docker_container:
        name: calculator
        image: chandrimanandi/calculator:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
