- name: Deploy Java Calculator container locally
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Ensure Docker Python SDK is installed
      pip:
        name: docker
        state: present

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: chandrimanandi/calculator
        tag: "{{ lookup('env','BUILD_ID') }}"
        source: pull

    - name: Run Java Calculator container
      docker_container:
        name: calculator
        image: "chandrimanandi/calculator:{{ lookup('env','BUILD_ID') }}"
        state: started
        restart_policy: always
        ports:
          - "9090:8080"
        command: "java -jar /app/calculator.jar"
