---
- name: Deploy Calculator container locally
  hosts: local
  become: true
  collections:
    - community.docker
  tasks:
    # - name: Ensure docker is installed
    #   apt:
    #     name: docker.io
    #     state: present
    #     update_cache: no

    - name: Ensure python docker SDK is present for Ansible modules
      pip:
        name: docker
        state: present

    - name: Use local Docker image
      community.docker.docker_image:
        name: calculator
        tag: latest
        source: local

    - name: Stop and remove existing container if present
      community.docker.docker_container:
        name: scientific_calculator
        state: absent
        force_kill: yes

    - name: Run container
      community.docker.docker_container:
        name: scientific_calculator
        image: chandrimanandi/calculator:latest
        state: started
        restart_policy: always
        tty: yes
        interactive: yes
        command: python ./calculator.py
